### ISSUE TITLE
Missing dependencies in recipe

### ISSUE THREAD

**Issue by jacksund** [conda-forge/mkdocs-material-feedstock#141]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The recipe used for this feedstock is out of date compared to the main repo, causing `pip check` to fail in other CI.

Specifically, the dependencies have been updated:
https://github.com/squidfunk/mkdocs-material/blob/77655074f654012c16611ac0010781d304787a6e/requirements.txt#L30

To fix this, the following needs to be added to `recipe/meta.yaml`:
```
cairosvg>=2.5
pillow>=8.0
requests>=2.26
```

I'd also add `pip check` to the `test` section too -- to prevent repeat issues

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by thewchan** [comment]
I think we've updated the recipe in more recent versions to conform to upstream dependencies.
